# Font,Just a regular good looking font :)
font_family JetBrains Mono Nerd Font
#Default font size.
font_size 12

# Make the cursor shape a beam
cursor_shape beam
cursor_trail 1
# Padding
window_margin_width 10

#Fuck the closing confirmation
confirm_os_window_close 0


# Scroll back up to 3000 lines.
scrollback_lines 3000

#Use fish please
shell fish


# Just a keybind to change font size to your liking, it's CTRL + scroll wheel up or down.
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# Background opacity, set to 0 if you want blur/transparency.
# Blur works with hyprland, or sway-fx as a drop-in replacement for sway.
background_opacity 1

background_blur 400

copy_on_select yes
strip_trailing_spaces smart
# Finally, the COLORS! these use the design system I made for this rice.
cursor               #EDECE6


